name: ArgoCD Deployment Pipeline

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up ArgoCD CLI
    - name: Install ArgoCD CLI
      run: |
        curl -sSL https://github.com/argoproj/argo-cd/releases/download/v2.5.7/argocd-linux-amd64 -o /usr/local/bin/argocd
        chmod +x /usr/local/bin/argocd

    # Authenticate with ArgoCD (use your ArgoCD server URL)
    - name: ArgoCD Login
      run: |
        argocd login localhost:8081 --username "admin" --password "OFihMoVH0M3n5yJa" --insecure

    # Pull the file from the GitHub repository (if applicable)
    - name: Pull file from repo
      run: |
        curl -O https://raw.githubusercontent.com/${{ github.repository }}/TestingRange/file.yaml

    # Sync Application with ArgoCD (replace `your-application-name` with the actual ArgoCD app name)
    - name: Sync Application with ArgoCD
      run: |
        argocd app sync your-application-name --prune

    # Optionally, you can check the status of the ArgoCD application
    - name: Check ArgoCD App Status
      run: |
        argocd app get your-application-name
